# Generated by Django 3.0.8 on 2020-07-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='ainterest',
            field=models.BooleanField(default=True),
        ),
    ]
